/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.main;

/**
 *
 * @author Asus
 */
public class Calc extends javax.swing.JFrame {
    boolean notDecimal = true;
    double currentNumb = 0, prevNumb = 0;
    Integer posTen = 0;
    String operation = " + ";
    
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        numb2 = new javax.swing.JButton();
        numb1 = new javax.swing.JButton();
        numb3 = new javax.swing.JButton();
        numb4 = new javax.swing.JButton();
        numb5 = new javax.swing.JButton();
        numb6 = new javax.swing.JButton();
        numb7 = new javax.swing.JButton();
        numb8 = new javax.swing.JButton();
        numb9 = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        numb0 = new javax.swing.JButton();
        negaPos = new javax.swing.JButton();
        resultButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        subtButton = new javax.swing.JButton();
        percentButton = new javax.swing.JButton();
        timeButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        prevInput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("That Time I Was Reincarnated as a Calculator with Unparalleled Calculation Ability so I Became a Great Sage and A Hero While Accidentally Becoming a Deep Dark Dragon Lord of Destruction's Saint.");
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setResizable(false);

        numb2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numb2.setText("2");
        numb2.setToolTipText("");
        numb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numb2ActionPerformed(evt);
            }
        });

        numb1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numb1.setText("1");
        numb1.setToolTipText("");
        numb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numb1ActionPerformed(evt);
            }
        });

        numb3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numb3.setText("3");
        numb3.setToolTipText("");
        numb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numb3ActionPerformed(evt);
            }
        });

        numb4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numb4.setText("4");
        numb4.setToolTipText("");
        numb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numb4ActionPerformed(evt);
            }
        });

        numb5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numb5.setText("5");
        numb5.setToolTipText("");
        numb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numb5ActionPerformed(evt);
            }
        });

        numb6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numb6.setText("6");
        numb6.setToolTipText("");
        numb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numb6ActionPerformed(evt);
            }
        });

        numb7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numb7.setText("7");
        numb7.setToolTipText("");
        numb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numb7ActionPerformed(evt);
            }
        });

        numb8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numb8.setText("8");
        numb8.setToolTipText("");
        numb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numb8ActionPerformed(evt);
            }
        });

        numb9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numb9.setText("9");
        numb9.setToolTipText("");
        numb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numb9ActionPerformed(evt);
            }
        });

        decimal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        decimal.setText(".");
        decimal.setToolTipText("");
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });

        numb0.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numb0.setText("0");
        numb0.setToolTipText("");
        numb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numb0ActionPerformed(evt);
            }
        });

        negaPos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        negaPos.setText("+/-");
        negaPos.setToolTipText("");
        negaPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negaPosActionPerformed(evt);
            }
        });

        resultButton.setBackground(new java.awt.Color(255, 204, 0));
        resultButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        resultButton.setText("=");
        resultButton.setToolTipText("");
        resultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addButton.setText("+");
        addButton.setToolTipText("");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clearButton.setText("C");
        clearButton.setToolTipText("");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        subtButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        subtButton.setText("-");
        subtButton.setToolTipText("");
        subtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtButtonActionPerformed(evt);
            }
        });

        percentButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        percentButton.setText("%");
        percentButton.setToolTipText("");
        percentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentButtonActionPerformed(evt);
            }
        });

        timeButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        timeButton.setText("x");
        timeButton.setToolTipText("");
        timeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeButtonActionPerformed(evt);
            }
        });

        divButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        divButton.setText("÷");
        divButton.setToolTipText("");
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                        .addComponent(numb7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numb8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numb9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(buttonPanelLayout.createSequentialGroup()
                            .addComponent(negaPos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numb0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(resultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(buttonPanelLayout.createSequentialGroup()
                            .addComponent(numb1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numb2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numb3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(percentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(buttonPanelLayout.createSequentialGroup()
                            .addComponent(numb4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numb5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numb6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(timeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numb1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numb2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numb3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numb5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numb6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numb4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numb9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numb7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numb8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(negaPos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numb0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        result.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        result.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        result.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        prevInput.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(prevInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prevInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void expandNumb(Integer newNumb){
        if(notDecimal) {
            currentNumb *= 10;
            currentNumb += newNumb;
        } else {
            currentNumb += newNumb * Math.pow(0.1, posTen);
        }
        posTen++;
    }
    
    private void acceptInput(String input){
        result.setText(result.getText() + input);
        expandNumb(Integer.valueOf(input));
    }
    
    private void nextNumb(java.awt.event.ActionEvent evt, String symbol){
        prevInput.setText(String.valueOf(currentNumb));
        prevInput.setText(prevInput.getText() + symbol);
        operation = symbol;
        result.setText("");
        prevNumb = currentNumb;
        currentNumb = 0;
    }
    
    private void numb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numb2ActionPerformed
        acceptInput("2");
    }//GEN-LAST:event_numb2ActionPerformed

    private void numb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numb1ActionPerformed
        acceptInput("1");
    }//GEN-LAST:event_numb1ActionPerformed

    private void numb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numb3ActionPerformed
        acceptInput("3");
    }//GEN-LAST:event_numb3ActionPerformed

    private void numb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numb4ActionPerformed
        acceptInput("4");
    }//GEN-LAST:event_numb4ActionPerformed

    private void numb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numb5ActionPerformed
        acceptInput("5");
    }//GEN-LAST:event_numb5ActionPerformed

    private void numb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numb6ActionPerformed
        acceptInput("6");
    }//GEN-LAST:event_numb6ActionPerformed

    private void numb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numb7ActionPerformed
        acceptInput("7");
    }//GEN-LAST:event_numb7ActionPerformed

    private void numb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numb8ActionPerformed
        acceptInput("8");
    }//GEN-LAST:event_numb8ActionPerformed

    private void numb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numb9ActionPerformed
        acceptInput("9");
    }//GEN-LAST:event_numb9ActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
        // TODO add your handling code here:
        if(!result.getText().contains(".") & (result.getText().length() > 0 | result.getText().equals("0"))){
            String current = result.getText();
            result.setText(current + ".");
            notDecimal = false;
        }
    }//GEN-LAST:event_decimalActionPerformed

    private void numb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numb0ActionPerformed
        if(!result.getText().equals("0")){
            acceptInput("0");
        }
    }//GEN-LAST:event_numb0ActionPerformed

    private void negaPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negaPosActionPerformed
        currentNumb *= -1;
        result.setText(String.valueOf(currentNumb));
    }//GEN-LAST:event_negaPosActionPerformed

    private void resultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButtonActionPerformed
        prevInput.setText(prevInput.getText() + String.valueOf(currentNumb));
        
        switch(operation) {
            case " + ":
                result.setText(String.valueOf(prevNumb + currentNumb));
                currentNumb += prevNumb;
                break;
            case " - ":
                result.setText(String.valueOf(prevNumb - currentNumb));
                currentNumb -= prevNumb;
                break;
            case " x ":
                result.setText(String.valueOf(prevNumb * currentNumb));
                currentNumb *= prevNumb;
                break;
            case " ÷ ":
                result.setText(String.valueOf(prevNumb / currentNumb));
                currentNumb /= prevNumb;
                break;
        }
    }//GEN-LAST:event_resultButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        nextNumb(evt, " + ");
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        result.setText("");
        prevInput.setText("");
        currentNumb = 0;
        prevNumb = 0;
    }//GEN-LAST:event_clearButtonActionPerformed

    private void subtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtButtonActionPerformed
        nextNumb(evt, " - ");
    }//GEN-LAST:event_subtButtonActionPerformed

    private void percentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentButtonActionPerformed
        currentNumb /= 100;
        result.setText(String.valueOf(currentNumb));
    }//GEN-LAST:event_percentButtonActionPerformed

    private void timeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeButtonActionPerformed
        nextNumb(evt, " x ");
    }//GEN-LAST:event_timeButtonActionPerformed

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divButtonActionPerformed
        nextNumb(evt, " ÷ ");
    }//GEN-LAST:event_divButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton decimal;
    private javax.swing.JButton divButton;
    private javax.swing.JButton negaPos;
    private javax.swing.JButton numb0;
    private javax.swing.JButton numb1;
    private javax.swing.JButton numb2;
    private javax.swing.JButton numb3;
    private javax.swing.JButton numb4;
    private javax.swing.JButton numb5;
    private javax.swing.JButton numb6;
    private javax.swing.JButton numb7;
    private javax.swing.JButton numb8;
    private javax.swing.JButton numb9;
    private javax.swing.JButton percentButton;
    private javax.swing.JLabel prevInput;
    private javax.swing.JLabel result;
    private javax.swing.JButton resultButton;
    private javax.swing.JButton subtButton;
    private javax.swing.JButton timeButton;
    // End of variables declaration//GEN-END:variables
}
